import {mkdir,copyFile,readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {candleLux,stopDifference,fitExposure,linearDisplay} from './lighting-physics.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-10,`${a} ≠ ${b}`);
near(candleLux(1,1),1);near(candleLux(1,2),.25);near(candleLux(4,2),1);
near(stopDifference(1,100000),16.609640474436812);
near(stopDifference(100000,1),-16.609640474436812);
near(linearDisplay(100000,.18,0),.18);
for(const lux of [.01,.25,1,10,100,10000,100000]) near(linearDisplay(lux,.18,fitExposure(lux)),.18);
assert.ok(linearDisplay(1,.18,0)<.000003);
assert.ok(linearDisplay(100000,.18,fitExposure(1))>.999);
const html=await readFile('lighting-lab.html','utf8');
const js=await readFile('lighting-lab.js','utf8');
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
assert.equal(new Set(ids).size,ids.length,'Duplicate element ids');
for(const match of js.matchAll(/\$\('([^']+)'\)/g)) assert.ok(ids.includes(match[1]),`Missing #${match[1]}`);
const files=['lighting-lab.html','lighting-lab.css','lighting-lab.js','lighting-physics.mjs','brdf-viewer.html'];
await mkdir('dist',{recursive:true});
for(const file of files)await copyFile(file,`dist/${file}`);
await copyFile('lighting-lab.html','dist/index.html');
console.log('Built static site. Physics, exposure calibration, and page references verified.');
